# Generated by Django 5.1.5 on 2025-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_update_courses_8vo_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotutoria',
            name='url_zoom',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL de Zoom'),
        ),
    ]
